brew "act"
brew "asdf"
brew "awscli"
brew "bat"
brew "claude-code"
brew "eza"
brew "fzf"
brew "node"
brew "gh"
brew "lazygit"
brew "luarocks"
brew "neovim"
brew "protobuf"
brew "python-tk@3.14"
brew "ripgrep"
# brew "rust"
# brew "rustup"
# brew "tailscale"  -> curl -fsSL https://tailscale.com/install.sh | sh
brew "tree-sitter-cli"
brew "uv"
brew "yazi"
brew "zellij"
brew "zoxide"
# brew "zsh"  -> sudo apt install zsh
vscode "anyscalecompute.ray-distributed-debugger"
vscode "charliermarsh.ruff"
vscode "ms-azuretools.vscode-containers"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
uv "aichor-cli"
uv "keyring", with: ["keyrings-google-artifactregistry-auth==1.1.2"]
uv "magic-wormhole"
uv "maturin"
uv "ruff"
flatpak "app.zen_browser.zen"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.mastermindzh.tidal-hifi"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.todoist.Todoist"
flatpak "us.zoom.Zoom"
