return {}
-- return {
--   {
--     'zbirenbaum/copilot.lua',
--     cmd = 'Copilot',
--     build = ':Copilot auth',
--     event = 'InsertEnter',
--     opts = {
--       suggestion = { enabled = true, auto_trigger = false },
--       panel = { enabled = false },
--       filetypes = {
--         ['*'] = true,
--       },
--     },
--   },
  -- {
  --   'zbirenbaum/copilot-cmp',
  --   config = function()
  --     require('copilot_cmp').setup()
  --   end,
--   -- },
-- }
